### ISSUE TITLE
Issues with cloning envoy_api dependency when building using bazel

### ISSUE THREAD

**Issue by borancar** [istio/proxy#964]
Hey guys,

I'm getting issues cloning envoy_api when trying to use bazel to build istio proxy. I'm on commit 958606073fbfb8afc480946d4fc8339f191271ca. This issue looks like something envoy had a while back:
https://groups.google.com/forum/#!topic/envoy-dev/4WQqlxl0GiU
https://github.com/envoyproxy/envoy/pull/1041

```
boran@DESKTOP-8479JBA:~/go/src/istio.io/proxy$ bazel --output_user_root=build build -c dbg //src/envoy
Extracting Bazel installation...
.....................
ERROR: error loading package '': Encountered error while reading extension file 'bazel/repositories.bzl': no such package '@envoy_api//bazel': Traceback (most recent call last):
        File "/home/boran/go/src/istio.io/proxy/build/2be3c7dcececb186d1ef868d2c0d188a/external/bazel_tools/tools/build_defs/repo/git.bzl", line 67
                _clone_or_update(ctx)
        File "/home/boran/go/src/istio.io/proxy/build/2be3c7dcececb186d1ef868d2c0d188a/external/bazel_tools/tools/build_defs/repo/git.bzl", line 42, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning envoy_api:
+ cd /home/boran/go/src/istio.io/proxy/build/2be3c7dcececb186d1ef868d2c0d188a/external
+ cd /home/boran/go/src/istio.io/proxy/build/2be3c7dcececb186d1ef868d2c0d188a/external/envoy_api
+ git reset --hard fd1a8c4269910caa2d99bf919c0ad13fb3d70f4f
fatal: Could not parse object 'fd1a8c4269910caa2d99bf919c0ad13fb3d70f4f'.
+ git fetch
+ git reset --hard fd1a8c4269910caa2d99bf919c0ad13fb3d70f4f
fatal: Could not parse object 'fd1a8c4269910caa2d99bf919c0ad13fb3d70f4f'.
.
INFO: Elapsed time: 22.607s
```

The same happens on our internal CI which is using docker container with image istio/ci:go1.9-bazel0.7

**Comment by qiwzhang** [comment]
@lizan could you help?

**Comment by lizan** [comment]
@borancar If you build without `--output_user_root=build` does the issue still reproduce? I don't think you can put the output user root inside the checked out source.

**Comment by lizan** [comment]
I can reproduce same output when with `--output_user_root=build`, but build works fine without it. Closing, feel free to reopen if you still see this.
